### ISSUE TITLE
Bug on unquote internally

### ISSUE THREAD

**Issue by mvicens** [mathxlee/gulp-css-url-quotes#2]
If we have, for example:

```css
.form-select {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='%23343a40' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m2 5 6 6 6-6'/%3e%3c/svg%3e");
}
```

This plugin transforms to:

```css
.form-select {
  background-image: url("data:image/svg+xml,%3csvg xmlns=http://www.w3.org/2000/svg viewBox=0 0 16 16%3e%3cpath fill=none stroke=%23343a40 stroke-linecap=round stroke-linejoin=round stroke-width=2 d=m2 5 6 6 6-6/%3e%3c/svg%3e");
}
```

... removing the single quotes of attributes. This is considered an error by PostCSS (shows [this error](https://github.com/svg/svgo/issues/1255)).
